# -*- coding: utf-8 -*-
"""Guess the number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15VULtf9Pw5SLoiVpnjKBvJKOu5mchVHu
"""

secret_number=9
guess_count=1
guess_limit=3
while guess_count<=guess_limit:
    guess=int(input("guess the number: "))
    guess_count+=1
    if guess==9:
        print("you  won!")
        break
else:
    print("Sorry, you failed")